import diophantine_approximation_probabilistic_number_theory_foundation_canonical_lane_mathlib.GateLemmas
import diophantine_approximation_probabilistic_number_theory_foundation_canonical_lane_mathlib.FinalTheorem
